#%RAML 1.0 NamedExample
values:
  message: There are validation errors
  processor?: API Kit Validation
  errors?:  
    - #item 1
      "code": xxx-000
      "message": Password cannot be blank
    - #item 2
      "code": xxx-001
      "message": Username cannot be blank