#%RAML 1.0 NamedExample

values:
  message?: There are some 
  messages?:  
    - #item 1
      "code": xxx-000
      "message": discount amount needs approval
    - #item 2
      "code": xxx-001
      "message": scheduled for the weekend