#%RAML 1.0 NamedExample
values: 
  providers:
    - #provider 1
      id: 1
      companyName: IBeans
      documentNumber: '33611500000119'
      contacts:
        - #contact 1
          name: Pedro Leão
          email: pedro.leao@ibeans.com
          telephone: '11986519592'
          mobile: '11985452535'
      address:
          street: Av Paulista
          number: "202"
          complement: Apto 204
          country: Brazil
          state: São Paulo
          town: São Paulo
          zipCode: 01050-000
      comments: No comment
    - #provider 2
      id: 2
      companyName: PointCold
      documentNumber: '33611500000119'
      contacts:
        - #contact 1
          name: Carlos Alves
          email: carlos.alves@pointcold.com
          telephone: '11986519592'
          mobile: '11985452535'
      address:
          street: Av Paulista
          number: "364"
          complement: Apto 204
          country: Brazil
          state: São Paulo
          town: São Paulo
          zipCode: 01050-000
      comments: No comment