#%RAML 1.0 NamedExample
values:
  id: 1
  companyName: IBeans
  documentNumber: '33611500000119'
  contacts:
    - #contact 1
      name: Luiz Carvalho
      email: luiz.carvalho@ibeans.com
      telephone: '11986519592'
      mobile: '11985452535'
  address:
      street: Av Paulista
      number: "202"
      complement: Apto 204
      country: Brazil
      state: São Paulo
      town: São Paulo
      zipCode: 01050-000
  comments: No comment